[workspace]
resolver = "2"
members = [
    "crates/super-swipe-engine",
    "crates/swipe-types",
]

[workspace.package]
version = "0.1.6"
edition = "2021"
authors = ["Zimeng Xiong", "Diamond White"]
license = "MIT"
