[package]
name = "swipe-types"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
bincode = "2.0.1"
serde = { version = "1.0.228", features = ["derive"] }
